import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { execa } from 'execa';
import { CONFIG_DIR } from './config.js';
import type { Frequency } from './config.js';

export const SERVICE_NAME = 'dobby-update';
export const SCHEDULER_PATH = path.join(
  os.homedir(),
  '.config',
  'systemd',
  'user',
  `${SERVICE_NAME}.timer`,
);
export const SERVICE_PATH = path.join(
  os.homedir(),
  '.config',
  'systemd',
  'user',
  `${SERVICE_NAME}.service`,
);
export const TIMER_PATH = SCHEDULER_PATH;
export const AGENT_SCRIPT_PATH = path.join(CONFIG_DIR, 'dobby-agent.sh');

function onCalendar(freq: Frequency, hour: number): string {
  const hh = hour.toString().padStart(2, '0');
  if (freq === 'hourly') return 'hourly';
  if (freq === 'daily') return `*-*-* ${hh}:00:00`;
  return `Sun ${hh}:00:00`;
}

export type SchedulerInputs = {
  frequency: Frequency;
  scheduledHour: number;
  binPath: string;
  nodePath: string;
};

function buildEnvPath(nodePath: string): string {
  const home = process.env.HOME ?? '';
  const interactive = process.env.PATH ?? '';
  const nodeBinDir = path.dirname(nodePath);
  const defaults = [
    '/usr/local/bin',
    '/usr/bin',
    '/bin',
    `${home}/.local/bin`,
    `${home}/.npm-global/bin`,
    `${home}/.bun/bin`,
    `${home}/.opencode/bin`,
    nodeBinDir,
  ];
  const seen = new Set<string>();
  const merged: string[] = [];
  for (const part of interactive.split(':').concat(defaults)) {
    const p = part.trim();
    if (!p || seen.has(p)) continue;
    seen.add(p);
    merged.push(p);
  }
  return merged.join(':');
}

export function buildAgentScript(input: SchedulerInputs): string {
  const envPath = buildEnvPath(input.nodePath);
  return `#!/usr/bin/env bash
# Auto-generated by dobby. Re-run \`dobby enable\` to refresh.
export PATH='${envPath}'
exec ${input.nodePath} ${input.binPath} update
`;
}

export function buildServiceFile(): string {
  return `[Unit]
Description=Dobby background updater

[Service]
Type=oneshot
ExecStart=${AGENT_SCRIPT_PATH}
`;
}

export function buildTimerFile(input: SchedulerInputs): string {
  return `[Unit]
Description=Dobby update timer

[Timer]
OnCalendar=${onCalendar(input.frequency, input.scheduledHour)}
Persistent=true

[Install]
WantedBy=timers.target
`;
}

export async function writeAgentScript(input: SchedulerInputs): Promise<string> {
  await fs.mkdir(path.dirname(AGENT_SCRIPT_PATH), { recursive: true });
  await fs.writeFile(AGENT_SCRIPT_PATH, buildAgentScript(input), 'utf8');
  await fs.chmod(AGENT_SCRIPT_PATH, 0o755);
  return AGENT_SCRIPT_PATH;
}

export async function writeUnits(input: SchedulerInputs): Promise<{ service: string; timer: string }> {
  await fs.mkdir(path.dirname(SERVICE_PATH), { recursive: true });
  await fs.writeFile(SERVICE_PATH, buildServiceFile(), 'utf8');
  await fs.writeFile(TIMER_PATH, buildTimerFile(input), 'utf8');
  return { service: SERVICE_PATH, timer: TIMER_PATH };
}

export async function bootout(): Promise<void> {
  await execa('systemctl', ['--user', 'stop', `${SERVICE_NAME}.timer`], {
    reject: false,
  });
  await execa('systemctl', ['--user', 'disable', `${SERVICE_NAME}.timer`], {
    reject: false,
  });
}

export async function bootstrap(): Promise<void> {
  await execa('systemctl', ['--user', 'daemon-reload'], { reject: false });
  await execa('systemctl', ['--user', 'enable', `${SERVICE_NAME}.timer`], {
    reject: false,
  });
  await execa('systemctl', ['--user', 'start', `${SERVICE_NAME}.timer`], {
    reject: false,
  });
}

export async function reload(input: SchedulerInputs): Promise<void> {
  await bootout();
  await writeAgentScript(input);
  await writeUnits(input);
  await bootstrap();
}

export async function isLoaded(): Promise<boolean> {
  const res = await execa(
    'systemctl',
    ['--user', 'is-active', `${SERVICE_NAME}.timer`],
    { reject: false },
  );
  return res.exitCode === 0;
}

export async function removeFiles(): Promise<void> {
  for (const target of [SERVICE_PATH, TIMER_PATH, AGENT_SCRIPT_PATH]) {
    try {
      await fs.unlink(target);
    } catch (err: unknown) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }
}

export function describeNextRun(freq: Frequency, hour: number): string {
  if (freq === 'hourly') return 'every hour, on the hour';
  if (freq === 'daily') return `every day at ${hour.toString().padStart(2, '0')}:00 local`;
  return `every Sunday at ${hour.toString().padStart(2, '0')}:00 local`;
}
